### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation?

### ISSUE THREAD

**Issue by raravena80** [opcr-io/policy#87]
Hello opcr team,

I'm one of the co-chairs of the CNCF TAG-Runtime, I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, how the project uses OCI as a standard to manage OPA policies.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by gertd** [comment]
Hi Ricardo @raravena80 , I have added an agenda item to present/discuss/demo the project for Oct 6th .
-GertD

**Comment by raravena80** [comment]
Thanks! @gertd will Oct 20th work for you?  We have another presentation on Oct 6th and I thought Oct 20th might be better since you will get the full hour.

**Comment by gertd** [comment]
@raravena80 That works, I have update the agenda accordingly

**Comment by gertd** [comment]
The meeting occured at Oct 22, closing issue
