### ISSUE TITLE
Consider renaming the cli tool?

### ISSUE THREAD

**Issue by 06kellyjac** [opcr-io/policy#90]
`policy` is a very generic name and could clash with other projects such as selinux/policy or policyd and is quite non-descript/generic
I'm not aware of any specific popular binaries that go by the name `policy` but it is a possibility

Maybe `opcr` or `opolicyctl`?

**Comment by 06kellyjac** [comment]
related https://github.com/NixOS/nixpkgs/pull/194445

We called the package `opcr-policy` for now. The binary has been left as `policy`

**Comment by mihaibuzgau** [comment]
Hi @06kellyjac 

Thanks for working on adding the policy CLI to NixOS and for committing to maintaining it! We appreciate all the work you put into this.

We've discussed this matter internally and decided that we're going to keep the binary name as `policy` for now.

Please let us know if we can help with anything else.
