### ISSUE TITLE
Documented `go install` method fails with 0.1.43 due to `replace` directive.

### ISSUE THREAD

**Issue by bleggett** [opcr-io/policy#98]
This is the same bug as https://github.com/opcr-io/policy/issues/61 - but recently another `replace` directive was added in `go.mod` and the issue resurfaced, meaning people cannot install this CLI tool in the documented fashion.

Suggestion: Add a CI step that tests `go install`

**Comment by sakirma** [comment]
Hello,

I believe someone accidentally added back the replace to the go.mod folder. If you look back to the go.mod file, then you can see it again.

The reason why I am opening this issue again is because I can't run the `go install` command anymore on the latest tag.
